// <copyright file="IModelMapper.cs" company="Wavenet">
// Copyright (c) Wavenet. All rights reserved.
// </copyright>

namespace Wavenet.Umbraco8.ModelsMapper.Internal
{
    /// <summary>
    /// Internal interface used to determine if a class is generated by ModelsMapper.
    /// </summary>
    public interface IModelMapper
    {
    }
}